server.port=8081
spring.application.name=studentenwerk_simulator

# PostgreSQL (simulator_db)
spring.datasource.url=jdbc:postgresql://localhost:5433/simulator_db
spring.datasource.username=mensa
spring.datasource.password=mensa123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MQTT
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=studentenwerk_simulator
mqtt.topics.speiseplan=mensa/speiseplan
mqtt.topics.mensen=mensa/mensen
mqtt.topics.orders=mensa/orders
mqtt.topics.votes=mensa/votes
